version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - mongo-net
    volumes:
      - ${HOME}/.docker/database/mongo/data:/data/db
    ports:
      - ${MONGO_PORT}:27017

networks:
  mongo-net:
    driver: bridge
