version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - redis-net
    volumes:
      - ${HOME}.docker/cache/redis/data:/data

networks:
  redis-net:
    driver: bridge
